services:
  db:
    container_name: robots-database
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DJANGO_DATABASE_NAME}
      - POSTGRES_USER=${DJANGO_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
    env_file:
      - .env
  web:
    container_name: django-service
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${DJANGO_DATABASE_NAME}
      - POSTGRES_USER=${DJANGO_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
    depends_on:
      - db
    env_file:
      - .env
  user_program:
    container_name: user-program
    build: .
    command: sh -c "cd /code/robot && python3 main.py"
    volumes:
      - .:/code
    depends_on:
      - db
      - web
    env_file:
      - .env
  celery:
    container_name: celery
    build: .
    command: celery -A task1_beb worker -l INFO
    volumes:
      - .:/code
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
    depends_on:
      - web
      - redis
    env_file:
      - .env
  redis:
    container_name: redis
    image: "redis:alpine"
