[robot_info]
serial_number = '3'
production_date = '2023-01-11'
type = 'flying'
company = '3M'

[mqtt]
host = 'test.mosquitto.org'
port = '1883'
username = ''
password = ''
topic = 'task1_beb'
interval_time = '10'
