[robot_info]
serial_number = '1'
production_date = '2022-12-12'
type = 'flying'
company = 'BEB'

[mqtt]
host = 'test.mosquitto.org'
port = '1883'
username = ''
password = ''
topic = 'task1_beb'
interval_time = '10'
