[robot_info]
serial_number = 'R000001-37DH'
production_date = '26.12.2022'
type = 'flying'

[mqtt]
host = 'test.mosquitto.org'
port = '1883'
username = ''
password = ''
topic = 'task1_beb'
interval_time = '10'
