[robot_info]
serial_number = '00004'
production_date = '2022-12-26'
type = 'flying'
company = 'EcoTruck'

[mqtt]
host = 'test.mosquitto.org'
port = '1883'
username = ''
password = ''
topic = 'task1_beb'
interval_time = '10'
