[robot_info]
serial_number = '4'
production_date = '2023-01-07'
type = 'tracked'
company = 'LG Energy Solution'

[mqtt]
host = 'test.mosquitto.org'
port = '1883'
username = ''
password = ''
topic = 'task1_beb'
interval_time = '10'
