# Generated by Django 3.2.16 on 2023-02-19 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=256, unique=True)),
                ('nip', models.IntegerField(blank=True, null=True, unique=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('serial_number', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('production_date', models.DateField()),
                ('type', models.CharField(choices=[('4 wheeler', '4 wheeler'), ('amphibian', 'amphibian'), ('tracked', 'tracked'), ('flying', 'flying')], default='4 wheeler', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('telemetry', 'telemetry'), ('location', 'location')], default='telemetry', editable=False, max_length=10)),
                ('fault_detected', models.BooleanField(default=False, editable=False)),
                ('robot_id', models.ForeignKey(blank=True, db_column='robot_id', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.robot')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('telemetry_humidity', models.IntegerField(blank=True, default=0, editable=False)),
                ('telemetry_temperature', models.IntegerField(blank=True, default=0, editable=False)),
                ('telemetry_pressure', models.IntegerField(blank=True, default=0, editable=False)),
                ('location_latitude', models.IntegerField(blank=True, default=0, editable=False)),
                ('location_longitude', models.IntegerField(blank=True, default=0, editable=False)),
                ('sensor_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app1.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='RobotModificationHistory',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('robot_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app1.robot')),
            ],
        ),
    ]
