# Generated by Django 3.2.16 on 2023-02-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotlog',
            name='log_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app1.log'),
        ),
        migrations.AlterField(
            model_name='robotlog',
            name='robot_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app1.robot'),
        ),
    ]
