# Generated by Django 3.2.16 on 2023-01-09 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('production_date', models.DateField()),
                ('type', models.CharField(choices=[('4 wheeler', '4 wheeler'), ('amphibian', 'amphibian'), ('tracked', 'tracked'), ('flying', 'flying')], default='4 wheeler', max_length=10)),
                ('company', models.CharField(max_length=20)),
                ('telemetry_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('telemetry_humidity', models.CharField(default=0, editable=False, max_length=5)),
                ('telemetry_temperature', models.CharField(default=0, editable=False, max_length=5)),
                ('telemetry_pressure', models.CharField(default=0, editable=False, max_length=5)),
                ('location_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('location_latitude', models.CharField(default=0, editable=False, max_length=5)),
                ('location_longitude', models.CharField(default=0, editable=False, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RobotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_data', models.CharField(default=0, editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RobotHumidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_data', models.CharField(default=0, editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RobotPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_data', models.CharField(default=0, editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RobotTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_data', models.CharField(default=0, editable=False, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='robot',
            name='humidity_all',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robothumidity'),
        ),
        migrations.AddField(
            model_name='robot',
            name='pressure_all',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robotpressure'),
        ),
        migrations.AddField(
            model_name='robot',
            name='temperature_all',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robottemperature'),
        ),
        migrations.AddField(
            model_name='robot',
            name='timestamp_all',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robotdata'),
        ),
    ]
