# Generated by Django 3.2.16 on 2023-02-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotModificationHistory',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('robot_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app1.robot')),
            ],
        ),
    ]
