# Generated by Django 3.2.16 on 2023-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotlog',
            name='robot_id',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
