# Generated by Django 3.2.16 on 2023-01-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='robot_logs',
        ),
    ]
