# Generated by Django 3.2.16 on 2022-12-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('production_date', models.DateField()),
                ('type', models.CharField(choices=[('4 wheeler', '4 wheeler'), ('amphibian', 'amphibian'), ('tracked', 'tracked'), ('flying', 'flying')], default='4 wheeler', max_length=10)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
