# Generated by Django 3.2.16 on 2023-01-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230111_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_logs',
            field=models.ForeignKey(db_column='robot_logs', editable=False, on_delete=django.db.models.deletion.CASCADE, to='app1.robotlog'),
        ),
    ]
