# Generated by Django 3.2.16 on 2023-01-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230109_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='humidity_all',
            field=models.ForeignKey(db_column='humidity_all', db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robothumidity'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='pressure_all',
            field=models.ForeignKey(db_column='pressure_all', db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robotpressure'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='temperature_all',
            field=models.ForeignKey(db_column='temperature_all', db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robottemperature'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='timestamp_all',
            field=models.ForeignKey(db_column='timestamp_all', db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.robotdata'),
        ),
    ]
