# Generated by Django 3.2.16 on 2023-01-09 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230109_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotdata',
            name='robot_data',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, max_length=10),
        ),
    ]
