# Generated by Django 3.2.16 on 2023-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_robotdata_robot_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotdata',
            name='robot_data',
            field=models.DateTimeField(default=0, editable=False, max_length=10),
        ),
    ]
