# Generated by Django 3.2.16 on 2023-01-08 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230105_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
