# Generated by Django 3.2.16 on 2023-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_robotdata_robot_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotdata',
            name='robot_data',
            field=models.DateTimeField(editable=False),
        ),
    ]
