# Generated by Django 3.2.16 on 2023-01-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20230108_1341'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='robot',
            table=None,
        ),
    ]
