# Generated by Django 3.2.16 on 2023-01-11 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_robotdata_robot_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='humidity_all',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='location_timestamp',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='pressure_all',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='telemetry_timestamp',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='temperature_all',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='timestamp_all',
        ),
        migrations.AddField(
            model_name='robot',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='robot',
            name='company',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='location_latitude',
            field=models.CharField(default=0, editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='location_longitude',
            field=models.CharField(default=0, editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='serial_number',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_humidity',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_pressure',
            field=models.CharField(default=0, editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_temperature',
            field=models.CharField(default=0, editable=False, max_length=256),
        ),
        migrations.DeleteModel(
            name='RobotData',
        ),
        migrations.DeleteModel(
            name='RobotHumidity',
        ),
        migrations.DeleteModel(
            name='RobotPressure',
        ),
        migrations.DeleteModel(
            name='RobotTemperature',
        ),
    ]
