# Generated by Django 3.2.16 on 2023-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20230108_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotdata',
            name='serial_nb',
            field=models.CharField(default=0, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='robotdata',
            name='robot_data',
            field=models.CharField(default=0, editable=False, max_length=10),
        ),
    ]
