# Generated by Django 3.2.16 on 2023-01-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20230111_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='location_latitude',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='location_longitude',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_pressure',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_temperature',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
