# Generated by Django 3.2.16 on 2023-01-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20230108_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotdata',
            name='serial_nb',
        ),
        migrations.AlterField(
            model_name='robotdata',
            name='robot_data',
            field=models.CharField(max_length=10),
        ),
    ]
