# Generated by Django 3.2.16 on 2023-01-11 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20230111_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
