# Generated by Django 3.2.16 on 2023-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_robot_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='location_latitude',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='location_longitude',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_humidity',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_pressure',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='robot',
            name='telemetry_temperature',
            field=models.CharField(max_length=256),
        ),
    ]
