# Generated by Django 3.2.16 on 2023-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230108_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotHumidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_data', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RobotPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_data', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RobotTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_data', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='humidity_all',
            field=models.ManyToManyField(to='app1.RobotHumidity'),
        ),
        migrations.AddField(
            model_name='robot',
            name='pressure_all',
            field=models.ManyToManyField(to='app1.RobotPressure'),
        ),
        migrations.AddField(
            model_name='robot',
            name='temperature_all',
            field=models.ManyToManyField(to='app1.RobotTemperature'),
        ),
    ]
