# Generated by Django 3.2.16 on 2023-01-08 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20230108_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotdata',
            name='robot_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
